title: Mochapoo Pets
description: Expert pet care and breed guides
theme: minima
baseurl: ""
url: "https://pets.mochapoo.com"
markdown: kramdown
permalink: /:year/:month/:day/:title/
show_excerpts: true
minima:
  skin: dark
